script.js
Hi there, this is my code implementation of the "Fizz Buzz" challenge using pure JavaScript. 
Thanks.
=> Solved the FizzBuzz problem with Javascript language

algorithms/Circular_linked_list/circularlinkedlist.cpp
Here is the code for the implementation of Circular Linked List, Inserting the values in the beginning, in the end, after some value and also printing all the values in the end as a circular linked list.
=> Added the code for inserting and printing in Circular Linked List

algorithms/binary_search/binarysearch.java
Implemented in java with a detailed explanation.
=> Binary Search is added

find the largest prime factor/largestprimefactor.cpp
=> To find the largest prime factor

data_structures/single_linked_list/single_linked_list.cpp, data_structures/single_linked_list/single_linked_list.hpp
Implementation of the single linked list is in the hpp file because it uses templates.
Testing of the structure is done via asserts in the cpp file.
I'm happy about any feedback concerning the code.
=> added implementation of a single linked list

challenge/smallest_multiple/smallestMultiple.cpp
Here's the code for smallest multiple for any number from 1 to n. 
This is my first open source contribution, Thank you. It has been a pleasure contributing.
=> #24 smallest multiple

challenge/largest_palindrome.c
Signed-off-by: onurbbr <onurbuber@engineer.com>
=> Added largest palindrome solution

challenge/difference_of_the_squares/differenceOfSquares.cpp
Added solution to 'Difference of squares' under challenge/difference_of_the_squares/differenceOfSquares in solutionBranch
=> Solution to Difference of the squares

challenge/largest_palindrome_product/largest_palindrome.js
Function returns the first Palindrome starting from the largest 3 digit
create an array for all palindrome
using Math.max() method, get max number in the palindrome array
=> Largest Palindrome Product Fix

challenges/RemoveDuplicateElements/RemoveDuplicateElements.java
Using java, I created a method to remove duplicate elements in an array. I wrote unit test as well.
=> Remove duplicate elements solved

challenges/10001st_prime_number/solution1.cpp
The simple solution iterates through every integer ( i ) starting from the first prime (which we know is 2) and checks if i is prime by iterating through every integer ( j ) starting from 2 until the current number ( i ) is reached. For each value of j we check whether there is any remainder left after the division of i and j. If no remainder is left for any value of j we know the current number ( i ) is not prime.  We store each prime we find in a list. We iterate i until the list reaches 10001 elements and return the 10001st element.
=> My solution to the 10001st prime challenge.

challenges/pythagorean_triplet/solution.py
Please review the PR for: #37  .
Test:
=> Pythagorean triplet

challenges/smallest_multiple/smallestMultiple.cpp
Adjusted indentation and spacing
=> Refactor smallestMultiple.cpp

challenges/fizz_buzz/FizzBuzz.java
Solved Fizz Buzz problem #3 in Java ☕
=> Solution for Fizz Buzz problem #3 in Java ☕

programs/reverse_string/reverseString.js
Second attempt because I didn't include a user prompt in the first attempt. I think this time it looks a little better. Thanks for the patience!
=> Solution for reverseString in JavaScript

programs/reverse_string/reverse_string.cpp, programs/reverse_string/reverse_string.py
i fix some refactoring issue in reverse_string.cpp file and i add a python code to reverse a string
=> revers a string with Python

programs/checking_credentials/solution.py
Solve the checking credentials problem using Python 3.
=> Solve checking credentials

algorithms/quick_sort/quicksort.py
Quicksort algorithm written in Python 3.
=> Implement quicksort algorithm in Python

challenges/C/fizz_buzz/FizzBuzz.c
=> Add FizzBuzz (in C)

challenges/Java/string_reverse/StringReverse.java
This is a possible solution for issue #43
=> added a function to reverse a string

challenges/valid_email_password/test_valid_email_password.py, challenges/valid_email_password/valid_email_password.py
PR for : #51 
**Test Results**
=> Check valid email and password challenge

algorithms/C++/merge_sort/msort.cpp, algorithms/C++/merge_sort/msort.hpp
=> Add a C++ implementation of merge sort

challenges/C++/pythagorean_triplet/solution.cpp, challenges/C++/pythagorean_triplet/solution.hpp
=> A C++ Solution for Pythagorean Triplet

challenges/C/sum_of_primes/sum_of_primes.c
=> sum_of_primes: Added sum_of_primes.c

challenges/C/reverse_string/revWithLib.c, challenges/C/reverse_string/revWithoutLib.c
Signed-off-by: onurbbr <onurbuber@engineer.com>
=> Added reverse string codes

challenges/C/pythagorean_triplet/pythagorean_triplet.c
Signed-off-by: onurbbr <onurbuber@engineer.com>
=> pythagorean_triplet: added code to repo

challenges/C/fibonacci/fibonacci.c
Signed-off-by: Onur BÜBER <onurbuber@engineer.com>
=> fibonacci: added fibonacci series

programs/Javascript/reverse_string/binarySearchOnSortedArray.js
Javascript Binary Search file has been added in programs folder.
=> BinarySearchSorted added for issue  [#18]

challenges/Python/MergeSortedArrays/Mergesortarrays.py
Resolved Issue #38  that is a program to merge two sorted arrays using python
=> Python program to merge two sorted arrays -> Issue #38

challenges/Python/differenceofsquares/diffofsquaressum.py, challenges/Python/removeDuplicatesfromarray/removeduplfromarray.py
Added Python code to remove duplicates from an array -> Issue #34
=> Resolved Issue #34 using python

challenges/Python/reversingstring/revstring.py
Added Python code to reverse a string->Issue #43
=> Resolved Issue #43 using Python
